contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      ''
  - about: Get support on the Syscoin chat channels on Discord.
    name: Join the Syscoin support chat
    url: ''