on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: yarn test-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - run: yarn install
      - run: yarn test-all
