on:
  pull_request:
    branches:
      - main
      - v2-front
    types: [opened, synchronize]

jobs:
  test:
    name: yarn install and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn lint
